administrator/urls.py
from django.urls import path
from . import views

# Create your tests here.
app_name = "administrator"

urlpatterns = [
    path('', views.admin_home, name="home"),
    path('vehicle/<int:pk>', views.vehicle_view, name="vehicle"),
    path('vehicle/<int:pk>/delete', views.vehicle_delete.as_view(), name="delete"),
    path('driver/<int:pk>', views.driver_profile, name="driver"),
    path('driver/<int:pk>/driver_delete', views.driver_delete.as_view(), name="driver_delete"),
    # reports
    path('reports/', views.reports_landing, name="reports"),
]

driver/urls.py
from django.urls import path
from . import views
app_name = 'driver'
urlpatterns = [
    path('', views.index, name="home"),
    # path('login', views.loginPage, name="login"),
    # path('logout/', views.logout, name="logout"),
    # path('signup/', views.register, name="signup"),
    path('currentjourney/', views.currentjourney, name="currentjourney"),
    path('directions/', views.directions, name="directions"),
    path('trip/', views.trip, name="trip"),
    path('error/', views.error, name="error"),
    path('welcome/', views.landing, name="welcome"),
]

sendme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('driver.urls', namespace="driver")),
    path('agent/', include('administrator.urls', namespace='administrator')),
    path('co/', include('supadmin.urls', namespace='admin2')),
    path('accounts/', include('django.contrib.auth.urls')),
]
admin.site.site_header = "Drive Sure - Admin"
admin.site.site_title = "Drive Sure - Admin"
admin.site.index_title = "Welcome"
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models

# Create your models here.

administrator/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Count, Sum
from django.db.models.functions import TruncDate
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from driver.models import Profile, Vehicle, Journey, CompanyProfile


# Create your views here.


@login_required
def admin_home(request):
    current_user = request.user
    profiles = Profile.objects
    group = profiles.filter(user=current_user).values('Role')
    # company
    company_id = profiles.filter(user=current_user).values('company')[0]['company']
    company_name = CompanyProfile.objects.filter(id=company_id).values('registration_name')[0]['registration_name']

    # vehicles
    vehicles = Vehicle.objects.filter(company_id=company_id)
    # drivers
    drivers = profiles.filter(Role="Driver", company_id=company_id)
    journey = Journey.objects.prefetch_related('Vehicle').filter(Vehicle__company_id=company_id)
    counts = journey.values('StartTime') \
        .annotate(StartDate=TruncDate('StartTime')) \
        .order_by('StartDate') \
        .values('StartDate') \
        .annotate(**{'count': Count('StartTime')})

    dataset = [i for i in counts.values_list('count', flat=True)]
    dates = [dt.strftime('%d-%m-%Y') for dt in counts.values_list('StartDate', flat=True)]

    # vals =
    # print(vals)
    context = {
        'valueboxes': {
            'vehicle_count': vehicles.count(),
            'drivers': drivers.count(),
            'on_transit': journey.filter(JourneyStatus=True).count(),
            'total_journeys': journey.count()
        },
        'chart_data': {
            'labels': dates[-5:],
            'dataset': dataset[-5:]
        },
        'drivers': drivers,
        'vehicles2': vehicles,
        'user': current_user,
        'company_name': company_name
    }

    if group.values()[0]['Role'] == "Driver":
        return redirect("/")
    else:
        return render(request, "administrator/dashboard.html", context)


@login_required
def vehicle_view(request, pk):
    vehicle = Vehicle.objects.get(pk=pk)
    milage = Journey.objects.filter(Vehicle_id=pk)
    # print(milage.values())

    context = {
        'vehicle_details': {
            'RegistrationNumber': vehicle.VehicleID,
            'ChassisNumber': vehicle.ChasisNo,
            'EngineNumber': vehicle.EngineNo,
            'YearofManufacture': vehicle.YearofMan,
            'VehicleValue': vehicle.VahicleValue,
            'VehicleCapacity': vehicle.VehicleCapacity,
            'VehicleAvailability': vehicle.availability,
            'TLBLicence': vehicle.tlb_licence,
            'TLBExpirationDate': vehicle.tlb_licence_exp_date,
            'vehicle_id': vehicle.id
        }, 'milage': milage
    }

    return render(request, "administrator/vehicle.html", context)


class vehicle_delete(LoginRequiredMixin, generic.DeleteView):
    template_name = 'administrator/delete_vehicle.html'
    queryset = Vehicle.objects.all()

    def get_success_url(self):
        return reverse("administrator:home")


@login_required
def driver_profile(request, pk):
    profiles = Profile.objects.get(user_id=pk)
    # stats = profiles.aggregate(sum = Sum('Distance'))
    journey = Journey.objects.filter(Driver_id=pk)
    print(profiles.id)
    context = {
        'driver_details': profiles,
        'journey_stats': journey.aggregate(timetaken=Sum('Duration'),
                                           distance_trav=Sum('Distance'),
                                           TripsDone=Count('From')),
        'trips': journey
    }
    return render(request, "administrator/driver_profile.html", context)


class driver_delete(LoginRequiredMixin, generic.DeleteView):
    template_name = 'administrator/delete_driver.html'
    queryset = Profile.objects.all()

    def get_success_url(self):
        return reverse("administrator:home")


@login_required
def reports_landing(request):
    template_name = 'administrator/tabs_landing.html'
    profiles = Profile.objects
    current_user = request.user
    # company
    company_id = profiles.filter(user=current_user).values('company')[0]['company']
    print(company_id)
    journey = Journey.objects.prefetch_related('Vehicle'). \
        filter(Vehicle__company_id = company_id). \
        values(
        "From", "To", "Driver", "StartTime", "Driver_id", "EndTime", "Distance","Duration", "premium"
    )
    context = {
        'journey':journey
    }
    # print(journey)
    return render(request, template_name,context)

administrator/templates/administrator/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <marquee>
    <title>Drive Sure! - {{company_name}}</title>
  </marquee>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js"></script>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'assets/admin/plugins/font-awesome/css/font-awesome.min.css' %}">
  <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'assets/admin/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand bg-orange navbar-dark border-bottom">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
      </li>

    </ul>

    <!-- SEARCH FORM -->


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->

      <!-- Notifications Dropdown Menu -->


    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-light-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
<!--      <img src="{% static 'assets/admin/dist/img/logo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"-->
<!--           style="opacity: .8">-->
      <span class="brand-text font-weight-light">{{ company_name }}</span>
    </a>

    <!-- Sidebar -->
    {% block sidebar %}
    {% include 'partials/sidebar.html' %}
    {% endblock sidebar %}
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">
              {%  block page-title %}
              {%  endblock page-title %}
            </h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v2</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
        {% block valuestats %}
        {% endblock valuestats %}
        <!-- /.row -->


        <!-- /.row -->

        <!-- Main row -->
        {% block body %}

        {% endblock body %}
        <!-- /.row -->
      </div><!--/. container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-light">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-sm-none d-md-block">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2021 <a href="#">Drive Sure</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{% static 'assets/admin/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'assets/admin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'assets/admin/dist/js/adminlte.js' %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{% static 'assets/admin/dist/js/demo.js' %}"></script>

<!-- PAGE PLUGINS -->
<!-- SparkLine -->
<script src="{% static 'assets/admin/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<!-- jVectorMap -->
<script src="{% static 'assets/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'assets/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- SlimScroll 1.3.0 -->
<script src="{% static 'assets/admin/plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<!-- ChartJS 1.0.2 -->
<script src="{% static 'assets/admin/plugins/chartjs-old/Chart.min.js' %}"></script>

<!-- PAGE SCRIPTS -->
<script src="{% static 'assets/admin/dist/js/pages/dashboard2.js' %}"></script>

<script src="{% static 'assets/admin/plugins/datatables/jquery.dataTables.js' %}"></script>
<!--<script src="{% static 'assets/admin/plugins/datatables/dataTables.bootstrap4.js' %}"></script>-->
</body>
</html>

administrator/templates/administrator/dashboard.html
{% extends 'administrator/base.html' %}
{%  block page-title %}
     Dashboard
{%  endblock page-title %}
{% block valuestats %}
<div class="row">
  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box">
      <span class="info-box-icon bg-info elevation-1"><i class="fa fa-car"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Vehicles</span>
        <span class="info-box-number">
          {{ valueboxes.vehicle_count }}
          <small></small>
        </span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box mb-3">
      <span class="info-box-icon bg-danger elevation-1"><i class="fa fa-user"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Drivers</span>
        <span class="info-box-number">{{ valueboxes.drivers }}</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
  <!-- fix for small devices only -->
  <div class="clearfix hidden-md-up"></div>
  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box mb-3">
      <span class="info-box-icon bg-success elevation-1">
        <i class="fa fa-road"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">On Transit</span>
        <span class="info-box-number">{{ valueboxes.on_transit }}</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
  <div class="col-12 col-sm-6 col-md-3">
    <div class="info-box mb-3">
      <span class="info-box-icon bg-warning elevation-1"><i class="fa fa-users"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">All Trips</span>
        <span class="info-box-number">{{ valueboxes.total_journeys }}</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
</div>
{% endblock valuestats %}

{% block body %}
<div class="row">
    <div class="col-md-12">
            <div class="card">
              <div class="card-header">
<!--                <h3 class="card-title">Collapsible Accordion</h3>-->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div id="accordion">
                  <div class="row">
                    <!-- we are adding the .class so bootstrap.js collapse plugin detects it -->
                              <div class="col-md-12">
                    <p class="text-center">
                      <strong>Trips for the last 5 days</strong>
                    </p>

                    <div class="chart">
                      <!-- Sales Chart Canvas -->
                      <canvas id="myChart" height="180" style="height: 180px;"></canvas>
                    </div>
                    <!-- /.chart-responsive -->
                  </div>

                  </div>
                  <div class="card">
                    <div class="card-header">
                      <h4 class="card-title">
<!--                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">-->
                          Vehicles & Drivers
                        </a>
                      </h4>
                    </div>
<!--                    <div id="collapseTwo" class="panel-collapse collapse">-->
                      <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">Vehicles</div>
                                <div class="card-body">
                                  <table class="table table-condensed">
                  <tr>
                    <th>Vehicle ID</th>
                    <th>Vehicle Capacity</th>
                    <th style="width: 40px"></th>
                  </tr>
                  {% for i in vehicles2 %}
                                    <tr>
                                      <td>{{ i.VehicleID }}</td>
                                      <td>{{ i.VehicleCapacity }}</td>
                                      <td><a href="{% url 'administrator:vehicle' i.id %}">
                                          <button type="button" class="btn btn-block btn-primary btn-sm"><i class="fa fa-eye" aria-hidden="true"></i>
                                        view</button></a> </td>
                                    </tr>
                  {% endfor %}
                </table>
                                </div>
                            </div>

                            </div>
                        <div class="col-md-6">

                            <div class="card">
                                <div class="card-header">Drivers</div>
                                <div class="card-body">
                                  <table class="table table-condensed">
                  <tr>
                    <th>Surname</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>NationalID</th>
                  </tr>
                  {% for i in drivers %}
                      <tr>
                        <td>{{ i.Surname }}</td>
                        <td>{{ i.FirstName }}</td>
                        <td>{{ i.LastName }}</td>
                        <td>{{ i.NationalID }}</td>
                        <td><a href="{% url 'administrator:driver' i.user_id %}"><button type="button" class="btn btn-block btn-primary btn-sm"><i class="fa fa-eye" aria-hidden="true"></i>
                          view</button></a> </td>
                      </tr>
                  {% endfor %}
                </table>
                                </div>
                            </div>
                        </div>
                        </div>
                      </div>
<!--                    </div>-->
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
</div>

<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: {{ chart_data.labels | safe }},
        datasets: [
        {
        label               : [],
        backgroundColor     : 'green',
        strokeColor         : '#ced4da',
        pointColor          : '#ced4da',
        pointStrokeColor    : '#c1c7d1',
        pointHighlightFill  : '#fff',
        pointHighlightStroke: 'rgb(220,220,220)',
        data                : {{ chart_data.dataset | safe }}
      }
        ]
    },
    options: {
    showScale               : true,
    scaleShowGridLines      : false,
    scaleGridLineColor      : 'rgba(0,0,0,.05)',
    scaleGridLineWidth      : 1,
    scaleShowHorizontalLines: true,
    scaleShowVerticalLines  : true,
    bezierCurve             : true,
    bezierCurveTension      : 0.3,
    pointDot                : false,
    pointDotRadius          : 4,
    pointDotStrokeWidth     : 1,
    pointHitDetectionRadius : 20,
    datasetStroke           : true,
    datasetStrokeWidth      : 2,
    datasetFill             : true,
    maintainAspectRatio     : false,
    responsive              : true,
    legend                  : {display: false}

    }
});
</script>

{% endblock body %}

administrator/templates/administrator/delete_driver.html
{% extends 'administrator/base.html' %}

{%  block page-title %}
<!--<h1>Vehicle view</h1>-->
{%  endblock page-title %}
{% block body %}

<div class="row">
    <div class="col-md-12">
        <div class="card elevation-3 col-md-12">
            <div class="card-header">
                <div class="card-title">
                    <p>Delete Driver</p>
                </div>
            </div>
            <div class="card-body">
                <p> Are you sure you want to delete this Driver from the data base?</p>
                <p> Please note that this process is irreversible.</p>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i>
                                        Confirm Delete</button>
                </form>
               <a href="{% url 'administrator:home' %}"><button type="button" class="btn btn-success btn-sm mt-3"><i class="fa fa-arrow-left" aria-hidden="true"></i>
                                        Cancel</button></a>
            </div>
        </div>
    </div>

</div>

{% endblock body %}

administrator/templates/administrator/delete_vehicle.html
{% extends 'administrator/base.html' %}

{%  block page-title %}
<!--<h1>Vehicle view</h1>-->
{%  endblock page-title %}
{% block body %}

<div class="row">
    <div class="col-md-12">
        <div class="card elevation-3 col-md-12">
            <div class="card-header">
                <div class="card-title">
                    <p>Delete Vehicle</p>
                </div>
            </div>
            <div class="card-body">
                <p> Are you sure you want to delete this vehicle from the data base?</p>
                <p> Please note that this process is irreversible.</p>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i>
                                        Confirm Delete</button>
                </form>
               <a href="{% url 'administrator:home' %}"><button type="button" class="btn btn-success btn-sm mt-3"><i class="fa fa-arrow-left" aria-hidden="true"></i>
                                        Cancel</button></a>
            </div>
        </div>
    </div>

</div>

{% endblock body %}

administrator/templates/administrator/driver_profile.html
{% extends 'administrator/base.html' %}
{% load static %}
{%  block page-title %}
<h1>Driver Details</h1>
{%  endblock page-title %}
{% block body %}


    <div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle"
                       {% if driver_details.Gender == 'M' %}
                       src="{% static 'assets/img/male.jpg' %}"
                       {% else %}
                       src="{% static 'assets/img/female.jpg' %}"
                       {% endif %}
                       alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{driver_details.Surname}} {{driver_details.FirstName}} {{driver_details.LastName}}</h3>

                <p class="text-muted text-center">Driver</p>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>DL Number</b> <a class="float-right">{{journey_stats.Surname}}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Distance on the Road</b> <a class="float-right">{{journey_stats.distance_trav | floatformat }} Km</a>
                  </li>
                  <li class="list-group-item">
                    <b>Hours On the Road</b> <a class="float-right">{{journey_stats.timetaken }} </a>
                  </li>
                  <li class="list-group-item">
                    <b>Trips Made </b> <a class="float-right">{{journey_stats.TripsDone }} </a>
                  </li>
                </ul>

                <a href="{% url 'administrator:home' %}" class="btn btn-primary btn-block"><b>Back</b></a>
                <a href="{% url 'administrator:driver_delete' driver_details.id %}" class="btn btn-danger btn-block"><b>Remove this driver</b></a>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->

            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Trips Made</a></li>
                  <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Other Info</a></li>
<!--                  <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Settings</a></li>-->
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <div class="active tab-pane" id="activity">
                    <table id="example2" class="table table-bordered table-hover">
                    <thead> <tr>
                    <th>From</th>
                    <th>To</th>
                    <th>Distance</th>
                    <th>Departure</th>
                    <th>Arrival</th>
                    <th>Duration</th>
                    <th>Premium</th>
                  </tr></thead>
                  {% for i in trips %}
                      <tr>
                        <td>{{ i.From }}</td>
                        <td>{{ i.To }}</td>
                        <td>{{ i.Distance }}</td>
                        <td>{{ i.StartTime }}</td>
                        <td>{{ i.EndTime }}</td>
                        <td>{{ i.Duration }}</td>
                        <td>{{ i.premium }}</td>
                      </tr>
                  {% endfor %}
                </table>
                  </div>
                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="timeline">
                    <!-- The timeline -->

                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
          <!-- /.col -->
        </div>



{% endblock body %}

administrator/templates/administrator/vehicle.html
{% extends 'administrator/base.html' %}

{%  block page-title %}
<!--<h1>Vehicle view</h1>-->
{%  endblock page-title %}
{% block body %}

<div class="row">
    <div class="col-md-4">
        <div class="card elevation-3">
            <div class="card-header">
                <div class="card-title">
                    <p>Vehicle Details</p>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <tr>
                    <th>Particulars</th>
                    <th>Detail</th>
                  </tr>
                    <tr>
                      <td><p>Registration Number</p></td>
                      <td><p>{{vehicle_details.RegistrationNumber}}</p></td>
                    </tr>
                    <tr>
                      <td><p>Chassis Number</p></td>
                      <td><p>{{vehicle_details.ChassisNumber}}</p></td>
                    </tr>
                    <tr>
                      <td><p>Engine Number</p></td>
                      <td><p>{{vehicle_details.EngineNumber}}</p></td>
                    </tr>
                    <tr>
                      <td><p>Year of Manufacture</p></td>
                      <td><p>{{vehicle_details.YearofManufacture}}</p></td>
                    </tr>
                    <tr>
                      <td><p>Vehicle Value</p></td>
                      <td><p>{{vehicle_details.VehicleValue}}</p></td>
                    </tr>
                    <tr>
                      <td><p>Availability</p></td>
                      <td><p>{{vehicle_details.Availability}}</p></td>
                    </tr>
                    <tr>
                      <td><p>TLB Licence</p></td>
                      <td><p>{{vehicle_details.TLBLicence}}</p></td>
                    </tr>
                    <tr>
                      <td><p>TLB Expiration Date</p></td>
                      <td><p>{{vehicle_details.TLBExpirationDate}}</p></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card elevation-3">
            <div class="card-header">
                <div class="card-title">
                    <p mb-3> Activity </p>
                </div>
            </div>
            <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead> <tr>
                    <th>From</th>
                    <th>To</th>
                    <th>Distance</th>
                    <th>Departure</th>
                    <th>Arrival</th>
                    <th>Premium</th>
                  </tr></thead>
                  {% for i in milage %}
                      <tr>
                        <td>{{ i.From }}</td>
                        <td>{{ i.To }}</td>
                        <td>{{ i.Distance }}</td>
                        <td>{{ i.StartTime }}</td>
                        <td>{{ i.EndTime }}</td>
                        <td>{{ i.premium }}</td>
                      </tr>
                  {% endfor %}
                </table>
            </div>
        </div>
        <div class="card elevation-3">
            <div class="card-header">
                <div class="card-title">
                    <p mb-3> Actions </p>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <a href="{% url 'administrator:delete' vehicle_details.vehicle_id %}">
                            <button type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i>
                                Delete this Vehicle
                            </button>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a href="{% url 'administrator:home' %}">
                            <button type="button" class="btn btn-primary btn-sm">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });
</script>
{% endblock body %}