driver/urls.py
from django.urls import path
from . import views
app_name = 'driver'
urlpatterns = [
    path('', views.index, name="home"),
    # path('login', views.loginPage, name="login"),
    # path('logout/', views.logout, name="logout"),
    # path('signup/', views.register, name="signup"),
    path('currentjourney/', views.currentjourney, name="currentjourney"),
    path('directions/', views.directions, name="directions"),
    path('trip/', views.trip, name="trip"),
    path('error/', views.error, name="error"),
    path('welcome/', views.landing, name="welcome"),
]

sendme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('driver.urls', namespace="driver")),
    path('agent/', include('administrator.urls', namespace='administrator')),
    path('co/', include('supadmin.urls', namespace='admin2')),
    path('accounts/', include('django.contrib.auth.urls')),
]
admin.site.site_header = "Drive Sure - Admin"
admin.site.site_title = "Drive Sure - Admin"
admin.site.index_title = "Welcome"
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supadmin/urls.py
from django.urls import path
from . import views

app_name = 'supadmin'
urlpatterns = [
    path('', views.main_dashboard, name="admin_home"),
    # path('company', views.company.as_view(), name="company_list"),
    path('company', views.company, name="company_list"),
    path('company/<int:pk>', views.company_view, name="company_profile")
]

supadmin/models.py
from django.db import models

# Create your models here.

supadmin/views.py
from django.db.models import Count
from django.db.models.functions import TruncDate
from django.shortcuts import render
from django.views.generic import ListView
from driver.models import Vehicle, CompanyProfile, Profile, Journey
from .tables import SimpleTable


# Create your views here.

def main_dashboard(request):
    vehicles = Vehicle.objects.all()
    companies = CompanyProfile.objects.all()
    trips = Journey.objects.all()
    journeys = trips.values('StartTime') \
        .annotate(StartDate=TruncDate('StartTime')) \
        .order_by('StartDate') \
        .values('StartDate') \
        .annotate(**{'count': Count('StartTime')})

    print(journeys)
    drivers = Profile.objects.filter(Role='Driver')

    context = {
        'cards': {
            'v': vehicles.count(),
            'c': companies.count(),
            'd': drivers.count(),
            't': trips.count(),
        },
        'dates': [dt.strftime('%d-%m-%Y') for dt in journeys.values_list('StartDate', flat=True)],
        "counts": [i for i in journeys.values_list('count', flat=True)]
    }
    return render(request, "supadmin/dashboard.html", context)


def company(request):
    comp = CompanyProfile.objects.all()
    table = SimpleTable(comp)
    context = {
        'comp': comp,
        'table': table
    }
    return render(request, "supadmin/company_listing.html", context)


def company_view(request, pk):
    comp = CompanyProfile.objects.get(pk=pk)
    context = {
        'company':comp
    }
    return render(request, "supadmin/company_one.html",context)

supadmin/templates/supadmin/layouts/cards.html
<div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
        <div class="card-body ">
            <div class="row">
                <div class="col-5 col-md-4">
                    <div class="icon-big text-center icon-warning">
                        <i class="nc-icon nc-bus-front-12 text-warning"></i>
                    </div>
                </div>
                <div class="col-7 col-md-8">
                    <div class="numbers">
                        <p class="card-category">Vehicles</p>
                        <p class="card-title">{{cards.v}}
                        <p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer ">
            <hr>
            <div class="stats">
                <i class="fa fa-refresh"></i>
                Update Now
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
        <div class="card-body ">
            <div class="row">
                <div class="col-5 col-md-4">
                    <div class="icon-big text-center icon-warning">
                        <i class="fa fa-briefcase text-success"></i>
                    </div>
                </div>
                <div class="col-7 col-md-8">
                    <div class="numbers">
                        <p class="card-category">Companies</p>
                        <p class="card-title">{{cards.c}}
                        <p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer ">
            <hr>
            <div class="stats">
                <i class="fa fa-calendar-o"></i>
                Last day
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
        <div class="card-body ">
            <div class="row">
                <div class="col-5 col-md-4">
                    <div class="icon-big text-center icon-warning">
                        <i class="fa fa-users text-danger"></i>
                    </div>
                </div>
                <div class="col-7 col-md-8">
                    <div class="numbers">
                        <p class="card-category">Drivers</p>
                        <p class="card-title">{{cards.d}}
                        <p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer ">
            <hr>
            <div class="stats">
                <i class="fa fa-clock-o"></i>
                In the last hour
            </div>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6 col-sm-6">
    <div class="card card-stats">
        <div class="card-body ">
            <div class="row">
                <div class="col-5 col-md-4">
                    <div class="icon-big text-center icon-warning">
                        <i class="fa fa-road text-primary"></i>
                    </div>
                </div>
                <div class="col-7 col-md-8">
                    <div class="numbers">
                        <p class="card-category">Trips Made</p>
                        <p class="card-title">{{cards.t}}
                        <p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer ">
            <hr>
            <div class="stats">
                <i class="fa fa-refresh"></i>
                Update now
            </div>
        </div>
    </div>
</div>

supadmin/templates/supadmin/layouts/sidebar.html
<div class="sidebar" data-color="white" data-active-color="danger">
    <div class="logo">
        <a href="{% url 'supadmin:admin_home' %}" class="simple-text logo-mini">
            <div class="logo-image-small">
                <img src="../assets/img/logo-small.png">
            </div>
            <!-- <p>CT</p> -->
        </a>
        <a href="{% url 'supadmin:admin_home' %}" class="simple-text logo-normal">
            Creative Tim
            <!-- <div class="logo-image-big">
              <img src="../assets/img/logo-big.png">
            </div> -->
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="active ">
                <a href="{% url 'supadmin:admin_home' %}">
                    <i class="nc-icon nc-bank"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a href="{% url 'supadmin:company_list' %}">
                    <i class="fa fa-briefcase"></i>
                    <p>Registered Companies</p>
                </a>
            </li>
<!--            <li>-->
<!--                <a href="./map.html">-->
<!--                    <i class="nc-icon nc-pin-3"></i>-->
<!--                    <p>Maps</p>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="./notifications.html">-->
<!--                    <i class="nc-icon nc-bell-55"></i>-->
<!--                    <p>Notifications</p>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="./user.html">-->
<!--                    <i class="nc-icon nc-single-02"></i>-->
<!--                    <p>User Profile</p>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="./tables.html">-->
<!--                    <i class="nc-icon nc-tile-56"></i>-->
<!--                    <p>Table List</p>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li>-->
<!--                <a href="./typography.html">-->
<!--                    <i class="nc-icon nc-caps-small"></i>-->
<!--                    <p>Typography</p>-->
<!--                </a>-->
<!--            </li>-->
        </ul>
    </div>
</div>