driver/urls.py
from django.urls import path
from . import views
app_name = 'driver'
urlpatterns = [
    path('', views.index, name="home"),
    # path('login', views.loginPage, name="login"),
    # path('logout/', views.logout, name="logout"),
    # path('signup/', views.register, name="signup"),
    path('currentjourney/', views.currentjourney, name="currentjourney"),
    path('directions/', views.directions, name="directions"),
    path('trip/', views.trip, name="trip"),
    path('error/', views.error, name="error"),
    path('welcome/', views.landing, name="welcome"),
]

sendme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('driver.urls', namespace="driver")),
    path('agent/', include('administrator.urls', namespace='administrator')),
    path('co/', include('supadmin.urls', namespace='admin2')),
    path('accounts/', include('django.contrib.auth.urls')),
]
admin.site.site_header = "Drive Sure - Admin"
admin.site.site_title = "Drive Sure - Admin"
admin.site.index_title = "Welcome"
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

driver/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Surname = models.CharField(max_length=120, null=True)
    FirstName = models.CharField(max_length=120, null=True)
    LastName = models.CharField(max_length=120, null=True)
    NationalID = models.CharField(max_length=20, null=True)
    Gender = models.CharField(max_length=10, choices=[
        ('M', 'Male'),
        ('F', 'Female'),
    ])
    YearsofExp = models.IntegerField(null=True)
    company = models.ForeignKey('CompanyProfile', on_delete=models.SET_NULL, null=True, blank=True)
    Role = models.CharField(max_length=10, choices=[
        ('Admin', 'Administartor'),
        ('Driver', 'Driver'),
    ], null=True)
    ProfilePic = models.ImageField(upload_to="ProilePics/", blank=True, null=True)

    # def __str__(self):
    #     return self.user


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Vehicle(models.Model):
    VehicleID = models.CharField(max_length=120, null=False)
    VehicleCapacity = models.IntegerField()
    ChasisNo = models.CharField(null=False, max_length=20)
    YearofMan = models.IntegerField(null=False)
    EngineNo = models.CharField(null=False, max_length=12)
    VahicleValue = models.DecimalField(decimal_places=2, null=False, max_digits=27)
    VehicleCapacity = models.IntegerField()
    availability = models.BooleanField(default=False)
    company = models.ForeignKey('CompanyProfile', on_delete=models.CASCADE, null=True, blank=True)
    tlb_licence = models.CharField(null=True, max_length=12)
    tlb_licence_exp_date = models.DateField(null=True)

    def __str__(self):
        return self.VehicleID


class Journey(models.Model):
    From = models.CharField(max_length=120, null=False)
    To = models.CharField(max_length=120, null=False)
    Distance = models.DecimalField(decimal_places=2, max_digits=12)
    Vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, null=True)
    Driver = models.ForeignKey(User, on_delete=models.CASCADE)
    JourneyStatus = models.BooleanField(blank=False, null=False)
    # Passengers = models.IntegerField(blank=False, null=False)
    StartTime = models.DateTimeField(auto_now=True)
    EndTime = models.DateTimeField(auto_now=False, null=True, blank=True)
    premium = models.DecimalField(decimal_places=2, max_digits=12, null=False)
    Duration = models.IntegerField(null=True)

    def __str__(self):
        return "From " + self.From + " to " + self.To


class PremiumRate(models.Model):
    YearlyRate = models.DecimalField(decimal_places=2, null=False, max_digits=3)
    DistRate = models.DecimalField(decimal_places=2, null=False, max_digits=12)
    Supervisor = models.ForeignKey(User, on_delete=models.CASCADE)


class CompanyProfile(models.Model):
    registration_number = models.CharField(null=False, max_length=200)
    registration_name = models.CharField(null=False, max_length=200)
    company_logo = models.ImageField(upload_to="ProilePics/", blank=True, null=True)

    def __str__(self):
        return self.registration_name

driver/forms.py
from django import forms
from .models import Journey, Profile, CompanyProfile
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class journery_init(forms.ModelForm):
    # title = forms.CharField(label=(u'Task name'))
    # description = forms.CharField(label=(u'Task description'))
    # url_start = forms.CharField(label=(u'Start page url'))
    # url_end = forms.CharField(label=(u'Final page url'))

    def __init__(self, *args, **kwargs):
        super(journery_init, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.form_action = '/currentjourney/'
        # self.helper.layout.append()
        self.helper.layout.append(Submit('save', 'Start Journey'))

    class Meta:
        model = Journey
        fields = "__all__"
        exclude = ('Distance', "Driver", "JourneyStatus", "EndTime", "premium",'Duration')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SignUpForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    # email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        # self.helper = FormHelper(self)
        # self.helper.form_method = 'post'
        # self.helper.form_action = '/welcome/'

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class profile_update(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('Surname', css_class='form-group col-md-4 mb-0'),
                Column('FirstName', css_class='form-group col-md-4 mb-0'),
                Column('LastName', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            'NationalID','Gender','company','Role',
            Submit('submit', 'Submit')
        )

    class Meta:
        model = Profile
        fields = ('Surname', 'FirstName', 'LastName', 'NationalID', 'Gender', 'company', 'Role')

driver/views.py
from django.contrib.auth.decorators import login_required
from .services import distance, premium, path_to_map
from .forms import  SignUpForm, profile_update
from .models import Journey, Vehicle, PremiumRate, Profile
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import journery_init
from datetime import datetime

from django.utils import timezone


# Create your views here.
def index(request):
    signup = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("/welcome")
    else:
        form = SignUpForm()

    current_user = request.user
    form = journery_init()
    # kdl

    submitbutton = 5
    context = {
        "journeyStatus": Journey.objects.filter(JourneyStatus=True, Driver=current_user.id).exists(),
        "form": form,
        'form2': signup
    }
    return render(request, "driver/index.html", context)


def currentjourney(request):
    current_user = request.user
    form = journery_init(request.POST or None)
    if form.is_valid():
        data = form.cleaned_data
        dist = distance(From=data['From'], To=data['To'])
        vehicle_stats = PremiumRate.objects.last()
        if dist == None:
            return redirect("/error")
        else:
            # calculatePremium

            journeystat = Journey.objects.filter(JourneyStatus=True, Driver=current_user.id, Vehicle=data['Vehicle'])
            vehicles_id, vehicle_reg, vehicle_value = \
                Vehicle.objects.filter(VehicleID=data['Vehicle']).values_list('id', 'VehicleID', 'VahicleValue')[0]
            premimum = premium(dist=dist, carValue=vehicle_value, rate=vehicle_stats.YearlyRate)
            df = (data['From'],data['To'], dist, current_user.id,vehicles_id, 1,premimum)
            journeystat = Journey(From=data['From'], To=data['To'], Distance=dist, Driver_id=current_user.id,
                                  Vehicle_id=vehicles_id, JourneyStatus=1, premium=premimum)
            journeystat.save()
            journeystat = Journey.objects.filter(JourneyStatus=True, Driver=current_user.id)

            pathtomap = path_to_map(From=data['From'], To=data['To'])
    else:
        journeystat = Journey.objects.filter(JourneyStatus=True, Driver=current_user.id)
        From = list(journeystat.values_list('From', flat=True))[0]
        To = list(journeystat.values_list('To', flat=True))[0]
        pathtomap = path_to_map(From, To)

    try:
        JourneyStatistics = {
            "From": list(journeystat.values_list('From', flat=True))[0],
            "To": list(journeystat.values_list('To', flat=True))[0],
            "Distance (km)": list(journeystat.values_list('Distance', flat=True))[0]
        }
    except:
        JourneyStatistics = False

    context = {
        "JourneyStat": JourneyStatistics,
        "pathtomap": pathtomap
    }
    return render(request, "driver/currentjourney.html", context)


def directions(request):
    context = {
        "webpage": 'https://www.google.com/maps/dir///'
    }
    return render(request, "driver/directions.html", context)


def trip(request):
    current_user = request.user
    # currentjourney
    JourneyStat = Journey.objects.filter(
        JourneyStatus=True,
        Driver=current_user.id).latest('StartTime')
    endjourney = datetime.now(timezone.utc) - JourneyStat.StartTime

    # close journey
    Journey(id=JourneyStat.id, EndTime=datetime.now(),
            Distance=JourneyStat.Distance,
            Driver_id=current_user.id,
            Vehicle_id=JourneyStat.Vehicle,
            JourneyStatus=False,
            Duration = round(endjourney.total_seconds()/3600),
            premium=JourneyStat.premium,
            From=JourneyStat.From, To=JourneyStat.To).save()
    context = {
        "webpage": '' + "5"
    }
    return render(request, "driver/trip_stat.html", context)


def error(request):
    context = {
        'e': "Mmmh,one of the towns you've entered is not correct.Please check and try again"
    }
    return render(request, "driver/error.html", context)

@login_required
def landing(request):
    current_user = request.user
    form1 = profile_update(request.POST)
    if form1.is_valid():
        data = form1.cleaned_data
        Profile.objects.filter(user=current_user).update(
                Surname=data['Surname'],
                FirstName=data['FirstName'],
                LastName=data['LastName'],
                NationalID=data['NationalID'],
                Gender=data['Gender'],
                company=data['company'],
                Role=data['Role'],
        )
        if data['Role'] == "Driver":
            # # assign group
            # user = request.user
            # group = Group.objects.get(name='Drivers')
            # user.groups.add(group)
            return redirect('/')
        else:
            # assign group
            # user = request.user
            # group = Group.objects.get(name='Administrator')
            # user.groups.add(group)
            return redirect("/agent")
    else:
        print('form1')
    context = {
        'user': current_user,
        'form': form1,
    }
    return render(request, "driver/landing.html", context)

driver/templates/driver/currentjourney.html
{% extends 'base.html' %}
 {% load static %}
{% block body %}
 <!--== Page Title Area Start ==-->
    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Current Journey Status</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Page Title Area End ==-->
     <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">
                {% if JourneyStat  %}
                    <div class="col-lg-6 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">
                			<h3>You are on the move!</h3>
							<div class="col-sm-12">
                                <ul class="list-group">
                                     {% for key,value in JourneyStat.items %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="col-sm-7" align="left"><strong>{{key}} :</strong></div>
                                    <div class="col-sm-5" align="right">{{value}}</div>
                                    </li>
                                    {% endfor %}
                                    </ul>
                            </div>
                		</div>
                		<div class="create-ac">
                			Safe Journey Drive Safely!
                		</div>
                		<div class="login-menu">
                            <a href="{% url 'driver:trip' %}"><button type="button"  class="btn btn-danger">End Journey</button></a> |
                            <a href="{{pathtomap}}" target="_blank"><button type="button"  class="btn btn-info">Transit Map</button></a>
                		</div>
                	</div>
                </div>
                {% else %}
                <div class="col-lg-6 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">
                			<h3>All trips Done.</h3>
                		</div>
                		<div class="create-ac">
                			Click Start to pick your next trip.
                		</div>
                		<div class="login-menu">
                            <a href="{% url 'driver:home' %}"><button type="button"  class="btn btn-success">Start</button></a>
                		</div>
                	</div>
                </div>
                {% endif %}
        	</div>
        </div>
    </section>
    <!--== Login Page Content End ==-->
{% endblock body %}

driver/templates/driver/directions.html
{% extends 'base.html' %}
 {% load static %}
{% block body %}
    <!--== Page Title Area Start ==-->
    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Login</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Page Title Area End ==-->
     <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">
                			<h3>Welcome Back!</h3>
							<iframe src = 'https://www.openstreetmap.org' style="border:2px solid red;" title="Iframe Example"></iframe>
                		</div>

<!--                		<div class="login-other">-->
<!--                			<span class="or">or</span>-->
<!--                			<a href="#" class="login-with-btn facebook"><i class="fa fa-facebook"></i> Login With Facebook</a>-->
<!--                			<a href="#" class="login-with-btn google"><i class="fa fa-google"></i> Login With Google</a>-->
<!--                		</div>-->
                		<div class="create-ac">
                			<p>Don't have an account? <a href="{% url 'driver:register' %}">Sign Up</a></p>
                		</div>
                		<div class="login-menu">
                			<a href="about.html">About</a>
                			<span>|</span>
                			<a href="contact.html">Contact</a>
                		</div>
                	</div>
                </div>
        	</div>
        </div>
    </section>
    <!--== Login Page Content End ==-->
{% endblock body %}

driver/templates/driver/error.html
{% extends 'base.html' %}
 {% load static %}

{% block body %}

    <!--== 404 Page Page Content Start ==-->
    <section id="page-404-wrap" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="page-404-content">
                    	<div class="number">
							<div class="four">4</div>
							<div class="four">0</div>
							<div class="four">4</div>
                    	</div>
                    	<h4>THAT'S AN ERROR</h4>
                    	<p>{{e}}</p>
                    	<a href="{% url 'driver:home' %}" class="btn-404-home"><i class="fa fa-home"></i>Go to Home</a>
                    </div>
                </div>
        	</div>
        </div>
    </section>
    <!--== 404 Page Page Content End ==-->

{% endblock body %}

driver/templates/driver/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 {% load static %}
{% block body %}


    <!--== Slider Area Start ==-->
    <section id="slider-area">
        <!--== slide Item One ==-->
        <div class="single-slide-item overlay">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5">

                        {% if request.user.is_authenticated %}
                        <div class="book-a-car">
<!--                             sign up-->

<!--                             end sign up-->

                            {% if journeyStatus %}
                                <h4>You Have an existing Journey.</h4>
                                 <a href="{% url 'driver:currentjourney' %}"><button type="button"  class="btn btn-success">View Details</button></a>
                            {% else %}
                                {% crispy form %}
                            {% endif %}
<!--                            <form action="index.html">-->
                                <!--== Pick Up Location ==-->

<!--                            </form>-->
                             </div>
                             {% else %}
                        <br/><br/>
                             <div class="login-page-content">
                		<div class="login-form" >
                			<h3>Sign Up</h3>
							<form action="" method="POST">
                                {% csrf_token %}
								<div class="username">
                                    {{form2.username.label}}
									{{ form2.username }}
								</div>
								<div class="password">
                                    {{form2.password1.label}}
									{{ form2.password1 }}
								</div>
                                <div class="password">
                                     {{form2.password2.label}}
									{{ form2.password2 }}
								</div>
								<div class="log-btn">
									<button type="submit"><i class="fa fa-check-square"></i> Sign Up</button>
								</div>
							</form>
                		</div>
                	</div>
                        {% endif %}


                    </div>

                    <div class="col-lg-7 text-right">
                        <div class="display-table">
                            <div class="display-table-cell">
                                <div class="slider-right-text">
                                    <h1>DRIVE SURE!</h1>
                                    <p>Quick,Efficient and Economical.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--== slide Item One ==-->
    </section>

{% endblock body %}

driver/templates/driver/landing.html
{% extends 'base.html' %}
 {% load static %}
{% block body %}
 <!--== Page Title Area Start ==-->
    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Welcome {{ user }}.</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                    </div>

                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Page Title Area End ==-->
     <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">
                {% include "layouts/profile.html" %}
        	</div>
        </div>
    </section>
    <!--== Login Page Content End ==-->

<script>
    $(function(){
$('a[title]').tooltip();
});

</script>

{% endblock body %}

driver/templates/driver/register_done.html
{% extends 'base.html' %}
 {% load static %}
{% load crispy_forms_tags %}
{% block body %}
    <!--== Page Title Area Start ==-->
    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Register</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                        <p>We are glad to have you on board.</p>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Page Title Area End ==-->
   <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">
                			<h3>Done</h3>
                		</div>
                		<div class="create-ac">
                			<p>Have an account? <a href="{% url 'login' %}">Log In</a></p>
                		</div>
                		<div class="login-menu">
                			<a href="about.html">About</a>
                			<span>|</span>
                			<a href="contact.html">Contact</a>
                		</div>
                	</div>
                </div>
        	</div>
        </div>
    </section>
    <!--== Login Page Content End ==-->
{% endblock body %}

driver/templates/driver/signup.html
{% extends 'base.html' %}
 {% load static %}
{% load crispy_forms_tags %}
{% block body %}
    <!--== Page Title Area Start ==-->
    <section id="page-title-area" class="section-padding overlay">
        <div class="container">
            <div class="row">
                <!-- Page Title Start -->
                <div class="col-lg-12">
                    <div class="section-title  text-center">
                        <h2>Register</h2>
                        <span class="title-line"><i class="fa fa-car"></i></span>
                        <p>We are glad to have you on board.</p>
                    </div>
                </div>
                <!-- Page Title End -->
            </div>
        </div>
    </section>
    <!--== Page Title Area End ==-->
   <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">
                			<h3>Sign Up</h3>

								{% crispy user_form %}


                		</div>
                		<div class="create-ac">
                			<p>Have an account? <a href="{% url 'login' %}">Log In</a></p>
                		</div>
                		<div class="login-menu">
                			<a href="about.html">About</a>
                			<span>|</span>
                			<a href="contact.html">Contact</a>
                		</div>
                	</div>
                </div>
        	</div>
        </div>
    </section>
    <!--== Login Page Content End ==-->
{% endblock body %}

driver/templates/driver/trip_stat.html
{% extends 'base.html' %}
 {% load static %}
{% block body %}
 <!--== Page Title Area Start ==-->
   
    <!--== Page Title Area End ==-->
     <!--== Login Page Content Start ==-->
    <section id="lgoin-page-wrap" class="section-padding">
        <div class="container">
            <div class="row">

                <div class="col-lg-6 col-md-8 m-auto">
                	<div class="login-page-content">
                		<div class="login-form">
                			<h3>Journey Ended Successfully.</h3>
                		</div>
                		<div class="create-ac">
                			Click Start to pick your next trip.
                            {{info}}
                		</div>
                		<div class="login-menu">
                            <a href="{% url 'driver:home' %}"><button type="button"  class="btn btn-success">Start</button></a>
                		</div>
                	</div>
                </div>

        	</div>
        </div>
    </section>
    <!--== Login Page Content End ==-->



{% endblock body %}