driver/urls.py
from django.urls import path
from . import views
app_name = 'driver'
urlpatterns = [
    path('', views.index, name="home"),
    # path('login', views.loginPage, name="login"),
    # path('logout/', views.logout, name="logout"),
    # path('signup/', views.register, name="signup"),
    path('currentjourney/', views.currentjourney, name="currentjourney"),
    path('directions/', views.directions, name="directions"),
    path('trip/', views.trip, name="trip"),
    path('error/', views.error, name="error"),
    path('welcome/', views.landing, name="welcome"),
]

sendme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('driver.urls', namespace="driver")),
    path('agent/', include('administrator.urls', namespace='administrator')),
    path('co/', include('supadmin.urls', namespace='admin2')),
    path('accounts/', include('django.contrib.auth.urls')),
]
admin.site.site_header = "Drive Sure - Admin"
admin.site.site_title = "Drive Sure - Admin"
admin.site.index_title = "Welcome"
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supadmin/urls.py
from django.urls import path
from . import views

app_name = 'supadmin'
urlpatterns = [
    path('', views.main_dashboard, name="admin_home"),
    # path('company', views.company.as_view(), name="company_list"),
    path('company', views.company, name="company_list"),
    path('company/<int:pk>', views.company_view, name="company_profile")
]

supadmin/models.py
from django.db import models

# Create your models here.

supadmin/views.py
from django.db.models import Count
from django.db.models.functions import TruncDate
from django.shortcuts import render
from django.views.generic import ListView
from driver.models import Vehicle, CompanyProfile, Profile, Journey
from .tables import SimpleTable


# Create your views here.

def main_dashboard(request):
    vehicles = Vehicle.objects.all()
    companies = CompanyProfile.objects.all()
    trips = Journey.objects.all()
    journeys = trips.values('StartTime') \
        .annotate(StartDate=TruncDate('StartTime')) \
        .order_by('StartDate') \
        .values('StartDate') \
        .annotate(**{'count': Count('StartTime')})

    print(journeys)
    drivers = Profile.objects.filter(Role='Driver')

    context = {
        'cards': {
            'v': vehicles.count(),
            'c': companies.count(),
            'd': drivers.count(),
            't': trips.count(),
        },
        'dates': [dt.strftime('%d-%m-%Y') for dt in journeys.values_list('StartDate', flat=True)],
        "counts": [i for i in journeys.values_list('count', flat=True)]
    }
    return render(request, "supadmin/dashboard.html", context)


def company(request):
    comp = CompanyProfile.objects.all()
    table = SimpleTable(comp)
    context = {
        'comp': comp,
        'table': table
    }
    return render(request, "supadmin/company_listing.html", context)


def company_view(request, pk):
    comp = CompanyProfile.objects.get(pk=pk)
    context = {
        'company':comp
    }
    return render(request, "supadmin/company_one.html",context)

supadmin/templates/supadmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>
        Paper Dashboard 2 by Creative Tim
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
          name='viewport'/>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="{% static '/assets/supadmin/paper/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static '/assets/supadmin/paper/css/paper-dashboard.css' %}" rel="stylesheet"/>
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'assets/supadmin/paper/demo/demo.css' %}" rel="stylesheet"/>
    <script src="https://https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <script rel="script" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>


</head>

<body class="">
<div class="wrapper ">
    {% block sidebar %}{% endblock sidebar %}
    <div class="main-panel">
        <!-- Navbar -->
        {% block nav %}{% endblock nav %}
        <!-- End Navbar -->
        {% block body %}{% endblock body %}

        <footer class="footer footer-black  footer-white" style="position:revert;">
            <div class="container-fluid">
                <div class="row">
                    <nav class="footer-nav">
                        <ul>
                            <li><a href="https://www.creative-tim.com" target="_blank">Creative Tim</a></li>
                            <li><a href="https://www.creative-tim.com/blog" target="_blank">Blog</a></li>
                            <li><a href="https://www.creative-tim.com/license" target="_blank">Licenses</a></li>
                        </ul>
                    </nav>
                    <div class="credits ml-auto">
              <span class="copyright">
                © <script>
                  document.write(new Date().getFullYear())
                </script>, made with <i class="fa fa-heart heart"></i> by Creative Tim
              </span>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
<!--   Core JS Files   -->
<script src="{% static '/assets/supadmin/paper/js/core/jquery.min.js' %}"></script>
<script src="{% static '/assets/supadmin/paper/js/core/popper.min.js' %}"></script>
<script src="{% static '/assets/supadmin/paper/js/core/bootstrap.min.js' %}"></script>
<script src="{% static '/assets/supadmin/paper/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chart JS -->
<script src="{% static '/assets/supadmin/paper/js/plugins/chartjs.min.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static '/assets/supadmin/paper/js/plugins/bootstrap-notify.js' %}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static '/assets/supadmin/paper/js/paper-dashboard.min.js' %}" type="text/javascript"></script>
<!-- Paper Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static '/assets/supadmin/paper/demo/demo.js' %}"></script>
<script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/assets-for-demo/js/demo.js
      demo.initChartsPages();
    });


</script>




</body>

</html>

supadmin/templates/supadmin/company_listing.html
{% extends 'supadmin/base.html' %}
{% load render_table from django_tables2 %}
{% block sidebar %}
{% include 'supadmin/layouts/sidebar.html' %}
{% endblock sidebar %}

<!-- Navbar -->
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="javascript:;">Paper Dashboard 2</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <i class="nc-icon nc-zoom-split"></i>
                        </div>
                    </div>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link btn-magnify" href="javascript:;">
                        <i class="nc-icon nc-layout-11"></i>
                        <p>
                            <span class="d-lg-none d-md-block">Stats</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item btn-rotate dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="nc-icon nc-bell-55"></i>
                        <p>
                            <span class="d-lg-none d-md-block">Some Actions</span>
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-rotate" href="javascript:;">
                        <i class="nc-icon nc-settings-gear-65"></i>
                        <p>
                            <span class="d-lg-none d-md-block">Account</span>
                        </p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock nav %}
<!-- End Navbar -->
{% block body %}
<div class="content">
    <div class="row">
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header ">
                    <h3 class="card-title"><i class="fa fa-briefcase"> Registered Company Listing</i></h3>
                </div>
                <div class="body m-5">

                    <table class="table " id="companies" style="width:100%">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Company Logo</th>
                            <th>Registration Number</th>
                            <th>Registration Name</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in comp %}
                        <tr>
                            <td>{{ i.id }}</td>
                            <td><img src="{{i.company_logo}}"></td>
                            <td>{{i.registration_number}}</td>
                            <td>{{i.registration_name}}</td>
                            <td>
                                <a href="{% url 'supadmin:company_profile' i.id %}" class="btn btn-success btn-xs"><i class="fa fa-eye"></i> open</a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>#</th>
                            <th>Company Logo</th>
                            <th>Registration Number</th>
                            <th>Registration Name</th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="card-footer ">
                    <hr>
                </div>
            </div>
        </div>
    </div>

</div>
<script>
$(document).ready(function() {
    $('#companies').DataTable();
} );
</script>
{% endblock body %}

supadmin/templates/supadmin/dashboard.html
{% extends 'supadmin/base.html' %}

{% block sidebar %}
{% include 'supadmin/layouts/sidebar.html' %}
{% endblock sidebar %}

<!-- Navbar -->
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="javascript:;">Paper Dashboard 2</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <i class="nc-icon nc-zoom-split"></i>
                        </div>
                    </div>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link btn-magnify" href="javascript:;">
                        <i class="nc-icon nc-layout-11"></i>
                        <p>
                            <span class="d-lg-none d-md-block">Stats</span>
                        </p>
                    </a>
                </li>
                <li class="nav-item btn-rotate dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="nc-icon nc-bell-55"></i>
                        <p>
                            <span class="d-lg-none d-md-block">Some Actions</span>
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-rotate" href="javascript:;">
                        <i class="nc-icon nc-settings-gear-65"></i>
                        <p>
                            <span class="d-lg-none d-md-block">Account</span>
                        </p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock nav %}
<!-- End Navbar -->
{% block body %}
<div class="content">
    <div class="row">
        {% block cards %}
        {% include 'supadmin/layouts/cards.html' %}
        {% endblock %}
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header ">
                    <h5 class="card-title">Trips made</h5>
                    <p class="card-category">Last 5 days</p>
                </div>
                <div class="card-body ">
                    <canvas id='myChart' width="350" height="200"></canvas>
                    <script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: {{ dates | safe }},
        datasets: [
        {
        label               : [],
        backgroundColor     : 'green',
        strokeColor         : '#ced4da',
        pointColor          : '#ced4da',
        pointStrokeColor    : '#c1c7d1',
        pointHighlightFill  : '#fff',
        pointHighlightStroke: 'rgb(220,220,220)',
        data                : {{ counts | safe }}
      }
        ]
    },
    options: {
    showScale               : true,
    scaleShowGridLines      : false,
    scaleGridLineColor      : 'rgba(0,0,0,.05)',
    scaleGridLineWidth      : 1,
    scaleShowHorizontalLines: true,
    scaleShowVerticalLines  : true,
    bezierCurve             : true,
    bezierCurveTension      : 0.3,
    pointDot                : false,
    pointDotRadius          : 4,
    pointDotStrokeWidth     : 1,
    pointHitDetectionRadius : 20,
    datasetStroke           : true,
    datasetStrokeWidth      : 2,
    datasetFill             : true,
    maintainAspectRatio     : false,
    responsive              : true,
    legend                  : {display: false}

    }
});

                    </script>
                </div>
                <div class="card-footer ">
                    <hr>
                    <div class="stats">
                        <i class="fa fa-history"></i> Updated 3 minutes ago
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock body %}